Update nuxtjs.yml

diff --git a/.github/workflows/nuxtjs.yml b/.github/workflows/nuxtjs.yml
--- a/.github/workflows/nuxtjs.yml
+++ b/.github/workflows/nuxtjs.yml
@@ -27,24 +27,24 @@ jobs:
           node-version: "20"
           cache: npm
 
-      - name: Setup Pages
-        uses: actions/configure-pages@v5
-        with:
-          static_site_generator: nuxt
-
       - name: Install dependencies
         run: npm install
 
-      - name: Static HTML export with Nuxt
+      - name: Generate static files
         run: npm run generate
 
+      - name: Debug Generate
+        run: |
+          echo "Listing current directory:"
+          ls -la
+          echo "Listing dist directory:"
+          ls -la ./dist || echo "dist directory not found"
+
       - name: Upload artifact
+        if: success()
         uses: actions/upload-pages-artifact@v3
         with:
           path: ./dist
-          
-      - name: List files
-        run: ls -R ./dist
 
   deploy:
     environment:
@@ -53,9 +53,6 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
-      - name: List files
-        run: ls -R ./dist
-        
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
